import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

// Import Bricolage Grotesque font
const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "https://res.cloudinary.com/dsc0hliud/image/upload/v1757953241/b6fd1a78-3471-4667-a483-ef612d867663.png", // 👈 Your favicon path
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={bricolage.variable}>
      <body className="antialiased ">
        <main>{children}</main>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
