type Project = {
  id: string;
  name: string;
  description: string;
  liveLink?: string;
  githubLink?: string;
  technologies: string[];
  multipleDescriptions: string[];
  images: string[];
};

export const allProjects: Project[] = [
  {
    id: "44",
    name: "Glamer",
    description:
      "Glamer is a blog / magazine-style HTML template featuring sections like blog posts, gallery, shop layout, categories, and contact pages. It offers a clean, modern design ideal for lifestyle, travel, or content-driven websites. However, many elements are placeholders or static, so it’s best used as a starting point rather than a fully functional site out of the box.",
    technologies: [
      "Html",
      "Css",
      "Javascript",
      "Gulp Js",
      "Scss",
      "Bootstrap",
      "Swiper Js",
      "Aos",
    ],
    multipleDescriptions: [
      "Magazine / Blog Layout – Perfect for content-driven sites with a focus on articles and visuals.",
      "Clean & Minimal Design – Elegant typography and balanced white space for a premium look.",
      "Featured / Hero Sections – Highlight top stories or categories in a visually appealing banner area.",
      "Gallery / Visual Emphasis – Includes gallery layouts to showcase images and media content.",
      "Shop / Product Preview – Comes with a demo e-commerce section suitable for product display.",
      "Category / Navigation Clarity – Simple and intuitive menu for easy site navigation.",
      "Responsive / Adaptive – Fully optimized for desktop, tablet, and mobile screens.",
      "Call to Action / Subscription Area – Space for newsletter signups or promotional banners.",
      "Contact & Social Links – Prebuilt pages for inquiries and social media connections.",
      "Placeholder Content / Static Demo – Contains sample data and images for demonstration purposes.",
    ],
    images: [
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443607/Screenshot_2025-10-14_180516_kurpc4.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443607/Screenshot_2025-10-14_180412_mzjmst.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443607/Screenshot_2025-10-14_180238_eubjfr.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443608/Screenshot_2025-10-14_180538_hoedpt.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443609/Screenshot_2025-10-14_180258_hpkj2b.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443609/Screenshot_2025-10-14_180157_v6mrhx.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443609/Screenshot_2025-10-14_180345_un0wwb.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443609/Screenshot_2025-10-14_180616_pjzjmk.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760443610/Screenshot_2025-10-14_180224_qytzqo.png",
    ],
    liveLink: "https://glamer.vercel.app",
  },
  {
    id: "4",
    name: "Edupls",
    description:
      "Edupls is a modern, education-oriented HTML template designed for online schools, universities, and e-learning platforms. It offers sections such as featured courses, services, FAQs, testimonials, instructor profiles, blog, and enrollment options. The design is polished, responsive, and structured to make course offerings clear and navigation intuitive. It’s ideal as a starting point for an education site or e-course portal.",
    technologies: [
      "Html",
      "Css",
      "Javascript",
      "Gulp Js",
      "Scss",
      "Bootstrap",
      "Swiper Js",
      "Aos",
    ],
    multipleDescriptions: [
      "Modern Educational Design – Clean and professional layout ideal for schools, universities, and online platforms.",
      "Fully Responsive – Optimized for all devices including desktop, tablet, and mobile.",
      "Multiple Home Variations – Offers several homepage styles to fit different educational institutions.",
      "Course Showcase Section – Highlights featured or popular courses with images, prices, and details.",
      "Instructor Profiles – Displays teacher information with bio, photo, and social links.",
      "Event & Blog Pages – Includes pages for upcoming events, news, and educational blogs.",
      "Smooth Animations & UI Elements – Provides subtle transitions and an engaging user experience.",
      "Student Testimonials – Section to showcase feedback and ratings from students.",
      "Contact & Admission Form – Ready-to-use forms for student inquiries or admissions.",
      "Built with Modern Technologies – Developed using HTML5, CSS3, Bootstrap 5, and JavaScript for optimal performance.",
    ],
    images: [
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723452435/edupls/sjia6fh9ozxxvfjjg9qi.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723453631/edupls/slgj8qwz1v7fytuzrvln.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723452435/edupls/wgjckbizvxumckprvnok.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723453629/edupls/tylvbyo02f9l7twx5pyw.png",
    ],
    liveLink: "https://tfhtml.themepul.com/edupls/demo/index.html",
  },
  {
    id: "2",
    name: "Reeni",
    description:
      "Reeni is a polished, modern personal portfolio HTML template made for freelancers, designers, developers, or creatives. It features sections like “About Me,” Services, Blog, Projects / Portfolio, and Contact, with clean layout, bold hero area, skill bars, client testimonials, and strong visual emphasis to showcase work and professionalism.",
    technologies: [
      "Html",
      "Css",
      "Javascript",
      "Gulp Js",
      "Scss",
      "Bootstrap",
      "Swiper Js",
      "Aos",
    ],
    multipleDescriptions: [
      "Hero / Intro Section – Prominent hero area with name, roles, and call-to-action to view portfolio.",
      "Skills & Experience Stats – Displays professional skills with progress bars and project statistics.",
      "Service / Offerings Section – Highlights provided services such as Web Design, UI/UX, and Development.",
      "Portfolio / Project Showcase – Organized display of latest work with multiple project layout styles.",
      "Testimonials / Client Feedback – Section for showcasing positive reviews and client experiences.",
      "Blog / News Section – Includes area for posting blogs, news updates, or articles.",
      "Contact / Get in Touch – Integrated contact form with email, phone, and address information.",
      "Navigation / Structure – Simple and clear navigation (Home, About, Services, Blog, Project, Contact).",
      "Design & Visuals – Clean modern interface with animations, typography, and responsive design.",
      "Placeholder / Demo Content – Contains sample images, text, and contact data for demonstration purposes.",
    ],
    images: [
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1741105476/ih3jvm47w4cpu8btdfmf.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1741105225/Screenshot_2025-02-10_111459_khefdf.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1741105551/mqrd4qrwkbfqxasxwpfj.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1741105607/lgolzroaxwi7wlgj4ieh.png",
    ],
    liveLink: "https://inversweb.com/product/html/reeni/index.html",
  },
  {
    id: "1",
    name: "Fincatch",
    description:
      "Fincatch is a professional HTML template crafted specifically for banking, finance, and fintech businesses. It offers modern, clean layouts and features suited for showcasing financial services, corporate offerings, investment products, and technology-driven finance solutions. The design is polished, responsive, and business-oriented, making it a strong choice for firms that want to project trust, credibility, and innovation online.",
    technologies: [
      "Html",
      "Css",
      "Javascript",
      "Gulp Js",
      "Scss",
      "Bootstrap",
      "Swiper Js",
      "Aos",
    ],
    multipleDescriptions: [
      "Corporate / Professional Design – Sleek layout with visual polish appropriate for financial brands.",
      "Service / Feature Sections – Dedicated areas to highlight services like loans, investments, consulting, etc.",
      "Statistics & Counters – Sections showing numbers, metrics, and financial figures to build trust.",
      "Team / Expert Profiles – Space to introduce key team members, advisors, or financial experts.",
      "Project / Case Studies – Showcase past works, success stories, or client case studies.",
      "Testimonials & Reviews – Client feedback sections for social proof and credibility.",
      "Pricing / Plan Tables – Prebuilt pricing or plan comparison tables for financial products.",
      "Blog / News Section – To share insights, articles, industry news, or updates.",
      "Subscription / Newsletter Form – For capturing leads and staying connected with prospects.",
      "Responsive & Modern Tech – Built using HTML5, CSS3, Bootstrap, with responsive behavior and modern visual effects.",
    ],
    images: [
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723454449/fincatch/mfpn4toaoxvjpgr1xqge.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723454450/fincatch/y3aw6ktolkkdinbumdil.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723454450/fincatch/uvfjzlghc4uebvapkwbs.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760431873/dymttt5ouhjwpwrlpumw_qewds6.jpg",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723454451/fincatch/ugtnrkuxlpcztt5hfuy5.png",
    ],
    liveLink:
      "https://preview.themeforest.net/item/fincatch-banking-finance-and-fintech-html-template/full_screen_preview/50438426?_ga=2.28308728.595027879.1706531740-680321896.1699898128",
  },

  {
    id: "5500",
    name: "Ema Ena",
    description:
      "Ema Ena offers high-converting landing pages designed to engage visitors and deliver real results. Their streamlined process ensures fast delivery without compromising quality.",
    technologies: [
      "Next js",
      "Typescript",
      "Tailwind Css",
      "Framer Motion",
      "Css",
      "Html",
    ],
    multipleDescriptions: [
      "Proven Conversion Frameworks: Utilizes over 100 tested layouts to convert visitors into customers.",
      "Agency-Level Design: Modern, premium designs tailored for your brand without the agency price tag.",
      "5-Day Guaranteed Delivery: Fast turnaround with a professional team delivering on time, every time.",
      "Transparent Pricing: Clear value with no hidden fees—what you see is what you pay.",
      "Unlimited Revisions: Ensures satisfaction with revisions until you're happy with the final result.",
      "SSL Secure & Money-Back Guarantee: Provides peace of mind with secure transactions and a satisfaction guarantee.",
      "Responsive Design: Optimized for all devices, ensuring a seamless user experience.",
      "SEO Optimized: Designed to rank higher in search results, enhancing visibility.",
      "Client Testimonials: Showcases real feedback from businesses who've seen real results.",
      "Limited Availability: Onboards only 5 new clients per month, ensuring personalized attention.",
    ],
    images: [
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760608085/f048adae-553b-456a-9805-d02285d2f509.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760608164/b1d013ba-433d-4a82-8f5c-973d0b67cda8.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760608184/3c5d0d5c-905c-46bc-9f1a-1a2edf82feec.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760608220/c8796e4d-8da6-4c5d-82c0-063aa1de4dcb.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760608247/3fafccba-08b7-4178-b513-d04e765e1c9d.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760608302/fc3ef75e-f0b7-4e84-a435-9dfe968827c6.png",
    ],
    liveLink: "https://ema-ena-landing-page.vercel.app/",
    githubLink: "https://github.com/fensami/ema-ena-landing-page",
  },
  {
    id: "550",
    name: "Framer",
    description:
      "Agency Co is a modern, responsive HTML template designed for creative agencies, digital studios, and marketing firms. Built with Vite and React, it offers a sleek, performance-optimized user interface with smooth animations and a clean layout. The template includes sections for services, portfolio, team, testimonials, and contact information, making it ideal for agencies looking to showcase their work and attract new clients.",
    technologies: [
      "Next js",
      "Typescript",
      "Tailwind Css",
      "Framer Motion",
      "Css",
      "Html",
    ],
    multipleDescriptions: [
      "Custom Furniture Design: Tailored pieces that reflect your personal style and enhance your space.",
      "Room Decoration & Styling: Expertly curated decor to create harmonious and inviting environments.",
      "Space Planning & Interior Layout: Optimized layouts that maximize functionality and flow.",
      "Home Renovations & Remodeling: Transformative renovations that breathe new life into your home.",
      "Lighting Design: Strategic lighting solutions that set the mood and highlight design elements.",
      "Virtual Interior Design Consultations: Remote consultations for personalized design advice and planning.",
      "Responsive Design: Seamless user experience across all devices, ensuring accessibility and ease of use.",
      "Modern UI Components: Utilizes Shadcn/UI for consistent and professional interface elements.",
      "Purple Color Scheme: Aesthetic purple gradient accents that enhance the visual appeal.",
      "Complete Content Sections: Well-organized content that guides users through the design journey.",
    ],
    images: [
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760607667/218fd35c-c9c2-43f7-9bd1-c0b5123f297e.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760607731/15bfe521-7b5f-4c68-b66f-b30fc25ff2f4.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760607761/a73f8c87-3098-452e-b322-4183d8f5f2fa.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760607893/e06164ee-762b-4f16-866c-9fc128baeaf5.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760607845/6e2b0224-e54e-4c66-8865-4ed4e62b5e3a.png",
    ],
    liveLink: "https://framer-clone-nine.vercel.app/",
    githubLink: "https://github.com/fensami/framer-clone",
  },
  {
    id: "5",
    name: "Sports Academy",
    description:
      "The Sports Academy website is a modern, responsive HTML template designed for sports training centers, athletic programs, and youth sports academies. It features a vibrant, user-friendly layout with sections for classes, coaches, events, and contact information, making it ideal for organizations aiming to promote their sports programs online.",
    technologies: [
      "Next.js",
      "Tailwind Css",
      "MongoDB",
      "Swiper Js",
      "Aos",
      "Html",
      "Css",
    ],
    multipleDescriptions: [
      "Responsive Design – Optimized for all devices including desktop, tablet, and mobile.",
      "Class Schedules – Dedicated section to display training schedules and upcoming classes.",
      "Coach Profiles – Individual pages for coaches with bios and contact information.",
      "Event Calendar – Section to showcase upcoming sports events and activities.",
      "Contact Form – Integrated form for inquiries and registrations.",
      "Gallery Section – Display of images showcasing training sessions and events.",
      "Testimonials – Client feedback section to build trust and credibility.",
      "Social Media Links – Easy access to social media profiles for community engagement.",
      "Modern Aesthetic – Clean and vibrant design appealing to a broad audience.",
      "Easy Customization – Built with HTML5 and CSS3 for straightforward updates.",
    ],
    images: [
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723478569/sports-academy/cnyzmkjkkeeezfjfjdsq.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723478567/sports-academy/qasrllmsy98vgsfoboao.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723478567/sports-academy/tuoib6hgvkq1d5uyac31.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723478569/sports-academy/n5xdqd20i90gerdygxlm.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1723478567/sports-academy/lhcreegdqjhgi2u7xr3u.png",
    ],
    liveLink: "https://sports-academy-a3723.web.app",
    githubLink: "https://github.com/fensami/sports-academy-client",
  },
  {
    id: "55",
    name: "AgencyCo",
    description:
      "Agency Co is a modern, responsive HTML template designed for creative agencies, digital studios, and marketing firms. Built with Vite and React, it offers a sleek, performance-optimized user interface with smooth animations and a clean layout. The template includes sections for services, portfolio, team, testimonials, and contact information, making it ideal for agencies looking to showcase their work and attract new clients.",
    technologies: [
      "React js",
      "Javascript",
      "Bootstrap",
      "Css",
      "Html",
      "Tailwind Css",
    ],
    multipleDescriptions: [
      "Responsive Design – Optimized for all devices including desktop, tablet, and mobile.",
      "Service Showcase – Dedicated sections to display services offered by the agency.",
      "Portfolio Gallery – Visual display of past projects with hover effects and lightbox functionality.",
      "Team Profiles – Section to introduce team members with photos and brief bios.",
      "Client Testimonials – Display of client feedback to build trust and credibility.",
      "Contact Form – Integrated contact form for inquiries and communication.",
      "Smooth Animations – Subtle animations for a dynamic user experience.",
      "SEO Optimized – Built with SEO best practices to enhance search engine visibility.",
      "Performance Optimized – Fast loading times and smooth interactions.",
      "Built with Vite and React – Utilizes modern web technologies for a scalable and maintainable codebase.",
    ],
    images: [
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760456374/Screenshot_2025-10-14_213724_lm2etw.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760456374/Screenshot_2025-10-14_213741_j1ixpq.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760456380/Screenshot_2025-10-14_213821_o1nkcw.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760456399/Screenshot_2025-10-14_213757_jmpv83.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760456374/Screenshot_2025-10-14_213811_y0aeea.png",
      "https://res.cloudinary.com/dsc0hliud/image/upload/v1760456373/Screenshot_2025-10-14_213834_f56oul.png",
    ],
    liveLink: "https://agency-co.vercel.app/",
    githubLink: "https://github.com/fensami/agencyCo",
  },
  // {
  //   id: "3",
  //   name: "Blog Project Api",
  //   description:
  //     "An online learning platform where instructors can publish courses and students can enroll.",
  //   technologies: ["Next.js", "MongoDB", "Stripe API"],
  //   multipleDescriptions: [
  //     "Instructor dashboard for course creation",
  //     "Payment integration with Stripe",
  //     "Secure login & registration",
  //     "Course progress tracking",
  //   ],
  //   images: [
  //     "https://res.cloudinary.com/dsc0hliud/image/upload/v1735621236/blog%20Project%20Api/xpnvwom5prf1g8ze4gb3.png",
  //   ],
  //   liveLink: "https://edulearn.vercel.app",
  //   githubLink: "https://github.com/username/edulearn",
  // },
];
